####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-verteq
Description: OPM Vertical Equilibrium library
Version: 2015.10
Label: 2015.10
Maintainer: roland.kaufmann@uni.no
MaintainerName: Roland Kaufmann
Url: http://opm-project.org
Depends: opm-core
