####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-verteq
Description: OPM Vertical Equilibrium library
Version: 2016.04-pre
Label: 2016.04-pre
Maintainer: roland.kaufmann@uni.no
MaintainerName: Roland Kaufmann
Url: http://opm-project.org
Depends: opm-core opm-output
